### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by jfals82** [whileman133/rrtf#1]
Can you give an example of a multicolumn section? 🙏

**Comment by jfals82** [comment]
I was able to support columns using tables as detailed here:  https://github.com/clbustos/rtf/blob/master/examples/example02.rb

**Comment by whileman133** [comment]
Tables work, but the following should define a multicolumn section:

```ruby
# start a new two-column section
rtf.section("columns" => 2)
rtf.paragraph << "Section Text"
```
